plugins {
    alias libs.plugins.androidLibrary
    alias libs.plugins.kotlinAndroid
    alias libs.plugins.kapt
    alias libs.plugins.hiltAndroid
}

android {
    namespace 'pro.megadedh.fooddelivery.features.basket.ui'
}

apply from: "$project.rootDir/config/module-config.gradle"

dependencies {

    // Feature dependencies
    api (projects.features.basket.api)
    implementation (projects.features.basket.presentation)

    // Common dependencies
    implementation (projects.core.ui)
    implementation (projects.core.presentation)
    implementation (projects.common.ui)

    // Libs
    implementation libs.bundles.commonBundle
    implementation libs.bundles.uiBundle
    implementation libs.androidxFragment
    implementation libs.livedata
    kapt           libs.hiltCompiler
    implementation libs.coil
    implementation libs.timber
}